{
  "name": "novarestore-wiki",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "serve": "docusaurus serve",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear"
  },
  "dependencies": {
    "@docusaurus/core": "^3.10.0",
    "@docusaurus/preset-classic": "^3.10.0",
    "@docusaurus/faster": "^3.10.0",
    "prism-react-renderer": "^2.4.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
}
